// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScribeTrax.Context;

#nullable disable

namespace ScribeTrax.Migrations
{
    [DbContext(typeof(ScribeTraxDbContext))]
    [Migration("20251103175425_ChangeSubmissionDateToDateTime")]
    partial class ChangeSubmissionDateToDateTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScribeTrax.Models.Byline", b =>
                {
                    b.Property<int>("BylineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BylineId"));

                    b.Property<bool?>("Inactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BylineId")
                        .HasName("PK__Bylines__852A4D0CD47EF5F1");

                    b.HasIndex(new[] { "Name" }, "UQ_Bylines_Name")
                        .IsUnique();

                    b.ToTable("Bylines");
                });

            modelBuilder.Entity("ScribeTrax.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GenreId")
                        .HasName("PK__Genres__0385057EE1E1A1E8");

                    b.HasIndex(new[] { "Name" }, "UQ_Genres_Name")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("ScribeTrax.Models.Market", b =>
                {
                    b.Property<int>("MarketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarketId"));

                    b.Property<string>("Editor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Postal")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MarketId")
                        .HasName("PK__Markets__74B186AF60244A64");

                    b.HasIndex(new[] { "Name" }, "UQ_Markets_Name")
                        .IsUnique();

                    b.HasIndex(new[] { "Url" }, "UQ_Markets_Url")
                        .IsUnique()
                        .HasFilter("[Url] IS NOT NULL");

                    b.ToTable("Markets");
                });

            modelBuilder.Entity("ScribeTrax.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int?>("MarketId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<int?>("WorkId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A38C92E13DC");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ScribeTrax.Models.PaymentType", b =>
                {
                    b.Property<int>("PaymentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentTypeId")
                        .HasName("PK__PaymentT__BA430B354EC87EDD");

                    b.HasIndex(new[] { "Name" }, "UQ_PaymentTypes_Name")
                        .IsUnique();

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("ScribeTrax.Models.Submission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<int?>("BylineId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Fee")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("MarketId")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<bool?>("Royalty")
                        .HasColumnType("bit");

                    b.Property<bool?>("SelfPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WorkId")
                        .HasColumnType("int");

                    b.HasKey("SubmissionId")
                        .HasName("PK__Submissi__449EE1252922D03A");

                    b.HasIndex(new[] { "BylineId" }, "IX_Submissions_BylineId");

                    b.HasIndex(new[] { "MarketId" }, "IX_Submissions_MarketId");

                    b.HasIndex(new[] { "WorkId" }, "IX_Submissions_WorkId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("ScribeTrax.Models.Work", b =>
                {
                    b.Property<int>("WorkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkId"));

                    b.Property<int>("BylineId")
                        .HasColumnType("int");

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WorkId")
                        .HasName("PK__Works__2DE6D5F59CBD18EE");

                    b.HasIndex("BylineId");

                    b.HasIndex("GenreId");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("ScribeTrax.Models.Submission", b =>
                {
                    b.HasOne("ScribeTrax.Models.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId");

                    b.HasOne("ScribeTrax.Models.Work", "Work")
                        .WithMany()
                        .HasForeignKey("WorkId");

                    b.Navigation("Market");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("ScribeTrax.Models.Work", b =>
                {
                    b.HasOne("ScribeTrax.Models.Byline", "Byline")
                        .WithMany()
                        .HasForeignKey("BylineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScribeTrax.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId");

                    b.Navigation("Byline");

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
